### ISSUE TITLE
NDI SDK issue

### ISSUE THREAD

**Issue by mycroftcanner** [keijiro/Rcam2#9] opened 2022-02-07 21:24 UTC
It seems really hard to find the 4.5 version of the NDI sdk. Only version 5 is accessible. 

Do you think it would be possible to make Rcam2 work with the reverse engineered [version](https://code.videolan.org/jbk/libndi) of libndi?

**Comment by mycroftcanner** [comment] 2022-02-07 23:13
I managed to compile the controller for iOS by pointing the manifest to version 2.0.3 of KlakNDI. 
I did the same for the visualiser but I can't figure out how to make it work. I see the bridge in the pull down menu but it doesn't seem to see my controller.

**Comment by keijiro** [comment] 2022-02-08 00:17
Your solution is right. The NDI SDK problem can be solved by upgrading KlakNDI.

Regarding the connection issue, I'd recommend testing with simpler samples, like the sample project of KlakNDI.

If it reproduces with the KlakNDI sample, please report it to the KlakNDI repository. If it only reproduces with Rcam2, please create a new issue about it.

I'm closing this issue because the original problem (NDI SDK) was solved.

**Closed as completed by keijiro** 2022-02-08 00:17 UTC
Labels: question

**Comment by mycroftcanner** [comment] 2022-02-08 00:23
Thanks! I was about to give up and then I realised that I had to start the visualiser first then start the controller.. Now everything works! This is really fun, many thanks again.
